# Instructors/GSI-Instructors

Instructors are the primary point of contact in the course.

## Roles

The roles of instructors include:

-   Designing the course syllabus

-   Leading one, two or three sections on MWF

-   Creating and disseminating course materials. These includes, but are not limited to:

    -   Labs

    -   Problem Sets

    -   In-class slides and handouts

    -   Quizzes and Exams

    -   Review material

    -   (to the tutors) solutions to these course materials

-   Holding office hours

-   Maintaining the course website

-   Answering questions on the class forum.

-   Administering exams

-   Posting final grades.

## Responsibilities

Instructor responsibilities include:

-   Assigning tutors to sections

-   Preparing a general lesson plan for each day of section and disseminating this plan to the tutors by a reasonable time before section

-   Disseminating solutions to in-class handouts, labs and problem sets to tutors by the time of assignment release

-   During class, walking around to groups and assessing their understanding of the material, as well as fielding and answering student questions

-   Creating rubrics for labs

-   Communicating with readers with regards to grading questions

-   Setting up meetings with tutors and readers regularly (weekly or biweekly)

-   Granting assignment extensions

-   Resolving exam conflicts

-   Arranging student accommodations
